author: Tuist
github_url: https://github.com/tuist/simctl
copyright: 'Copyright © from 2018 Pedro Piñera Buendía. All rights reserved.'
output: docs
module: ProjectDescription
clean: true
xcodebuild_arguments:
  - -project
  - simctl.xcodeproj
  - -scheme
  - simctl-Package
swift_version: '4.2'
min_acl: public
readme: README.md
