author: Tuist
github_url: https://github.com/tuist/simulator
copyright: 'Copyright © from 2018 Pedro Piñera Buendía. All rights reserved.'
output: docs
module: Simulator
clean: true
xcodebuild_arguments:
  - -project
  - Simulator.xcodeproj
  - -scheme
  - Simulator-Package
swift_version: '4.2.1'
min_acl: public
readme: README.md
